[tool.black]
line-length = 100

[tool.isort]
include_trailing_comma=true
multi_line_output=3

[tool.pylint."MESSAGES CONTROL"]
# TODO remove import error
disable = [
    "import-error",
    "fixme",
]